name: 功能請求
title: "[Feature]："
description: 如果想要新功能，可以在這裡提出
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        你也可以到 HiZollo 的官方伺服器提出建議：https://discord.gg/xUXTrYG2MZ
  - type: textarea
    id: feature
    attributes:
      label: 你想要什麼
      description: |
        請告訴我們你想要什麼樣的一個新功能
      placeholder: |
        使用上常常會覺得......
        如果有這樣的功能......
        其它的機器人......
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: 想法
      description: |
        你對這項功能實作上的一些想法
      placeholder: |
        請詳細告訴我們你對這個功能的期望
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: 其它
      description: |
        任何可以協助其他人了解你想要的功能的文字、圖片或檔案