export default Object.freeze({
  /* (1 <<  0) */ "CREATE_INSTANT_INVITE": "建立邀請",
  /* (1 <<  1) */ "KICK_MEMBERS": "踢出成員",
  /* (1 <<  2) */ "BAN_MEMBERS": "對成員停權",
  /* (1 <<  3) */ "ADMINISTRATOR": "管理者",
  /* (1 <<  4) */ "MANAGE_CHANNELS": "管理頻道",
  /* (1 <<  5) */ "MANAGE_GUILD": "管理伺服器",
  /* (1 <<  6) */ "ADD_REACTIONS": "新增反應",
  /* (1 <<  7) */ "VIEW_AUDIT_LOG": "檢視審核紀錄",
  /* (1 <<  8) */ "PRIORITY_SPEAKER": "優先發言者",
  /* (1 <<  9) */ "STREAM": "視訊通話",
  /* (1 << 10) */ "VIEW_CHANNEL": "檢視頻道",
  /* (1 << 11) */ "SEND_MESSAGES": "發送訊息",
  /* (1 << 12) */ "SEND_TTS_MESSAGES": "傳送文字朗讀訊息",
  /* (1 << 13) */ "MANAGE_MESSAGES": "管理訊息",
  /* (1 << 14) */ "EMBED_LINKS": "嵌入連結",
  /* (1 << 15) */ "ATTACH_FILES": "附加檔案",
  /* (1 << 16) */ "READ_MESSAGE_HISTORY": "讀取訊息歷史",
  /* (1 << 17) */ "MENTION_EVERYONE": "提及 @\u200beveryone、@\u200bhere 和所有身分組",
  /* (1 << 18) */ "USE_EXTERNAL_EMOJIS": "使用外部表情符號",
  /* (1 << 19) */ "VIEW_GUILD_INSIGHTS": "檢視 Server Insights",
  /* (1 << 20) */ "CONNECT": "連接",
  /* (1 << 21) */ "SPEAK": "說話",
  /* (1 << 22) */ "MUTE_MEMBERS": "將成員靜音",
  /* (1 << 23) */ "DEAFEN_MEMBERS": "讓成員拒聽",
  /* (1 << 24) */ "MOVE_MEMBERS": "移動成員",
  /* (1 << 25) */ "USE_VAD": "使用語音活動",
  /* (1 << 26) */ "CHANGE_NICKNAME": "更改暱稱",
  /* (1 << 27) */ "MANAGE_NICKNAMES": "管理暱稱",
  /* (1 << 28) */ "MANAGE_ROLES": "管理身分組",
  /* (1 << 29) */ "MANAGE_WEBHOOKS": "管理 Webhooks",
  /* (1 << 30) */ "MANAGE_EMOJIS_AND_STICKERS": "管理表情符號與貼圖",
  /* (1 << 31) */ "USE_APPLICATION_COMMANDS": "使用應用程式命令",
  /* (1 << 32) */ "REQUEST_TO_SPEAK": "請求發言",
  /* (1 << 33) */ "MANAGE_EVENTS": "管理活動",
  /* (1 << 34) */ "MANAGE_THREADS": "管理討論串",
  /* (1 << 35) */ "CREATE_PUBLIC_THREADS": "建立公開討論串",
  /* (1 << 36) */ "CREATE_PRIVATE_THREADS": "建立私人討論串",
  /* (1 << 37) */ "USE_EXTERNAL_STICKERS": "使用外部貼圖",
  /* (1 << 38) */ "SEND_MESSAGES_IN_THREADS": "在討論串中傳送訊息",
  /* (1 << 39) */ "USE_EMBEDDED_ACTIVITIES": "使用活動",
  /* (1 << 40) */ "MODERATE_MEMBERS": "禁言成員",
  
  /* (1 <<  0) */ "CreateInstantInvite": "建立邀請",
  /* (1 <<  1) */ "KickMembers": "踢出成員",
  /* (1 <<  2) */ "BanMembers": "對成員停權",
  /* (1 <<  3) */ "Administrator": "管理者",
  /* (1 <<  4) */ "ManageChannels": "管理頻道",
  /* (1 <<  5) */ "ManageGuild": "管理伺服器",
  /* (1 <<  6) */ "AddReactions": "新增反應",
  /* (1 <<  7) */ "ViewAuditLog": "檢視審核紀錄",
  /* (1 <<  8) */ "PrioritySpeaker": "優先發言者",
  /* (1 <<  9) */ "Stream": "視訊通話",
  /* (1 << 10) */ "ViewChannel": "檢視頻道",
  /* (1 << 11) */ "SendMessages": "發送訊息",
  /* (1 << 12) */ "SendTTSMessages": "傳送文字朗讀訊息",
  /* (1 << 13) */ "ManageMessages": "管理訊息",
  /* (1 << 14) */ "EmbedLinks": "嵌入連結",
  /* (1 << 15) */ "AttachFiles": "附加檔案",
  /* (1 << 16) */ "ReadMessageHistory": "讀取訊息歷史",
  /* (1 << 17) */ "MentionEveryone": "提及 @​everyone、@​here 和所有身分組",
  /* (1 << 18) */ "UseExternalEmojis": "使用外部表情符號",
  /* (1 << 19) */ "ViewGuildInsights": "檢視 Server Insights",
  /* (1 << 20) */ "Connect": "連接",
  /* (1 << 21) */ "Speak": "說話",
  /* (1 << 22) */ "MuteMembers": "將成員靜音",
  /* (1 << 23) */ "DeafenMembers": "讓成員拒聽",
  /* (1 << 24) */ "MoveMembers": "移動成員",
  /* (1 << 25) */ "UseVAD": "使用語音活動",
  /* (1 << 26) */ "ChangeNickname": "更改暱稱",
  /* (1 << 27) */ "ManageNicknames": "管理暱稱",
  /* (1 << 28) */ "ManageRoles": "管理身分組",
  /* (1 << 29) */ "ManageWebhooks": "管理 Webhooks",
  /* (1 << 30) */ "ManageEmojisAndStickers": "管理表情符號與貼圖",
  /* (1 << 31) */ "UseApplicationCommands": "使用應用程式命令",
  /* (1 << 32) */ "RequestToSpeak": "請求發言",
  /* (1 << 33) */ "ManageEvents": "管理活動",
  /* (1 << 34) */ "ManageThreads": "管理討論串",
  /* (1 << 35) */ "CreatePublicThreads": "建立公開討論串",
  /* (1 << 36) */ "CreatePrivateThreads": "建立私人討論串",
  /* (1 << 37) */ "UseExternalStickers": "使用外部貼圖",
  /* (1 << 38) */ "SendMessagesInThreads": "在討論串中傳送訊息",
  /* (1 << 39) */ "UseEmbeddedActivities": "使用活動",
  /* (1 << 40) */ "ModerateMembers": "禁言成員"
});