import { CHANNEL_DELETE } from "./CHANNEL_DELETE";
import { CHANNEL_UPDATE } from "./CHANNEL_UPDATE";
import { GUILD_CREATE } from "./GUILD_CREATE";
import { GUILD_DELETE } from "./GUILD_DELETE";
import { GUILD_UPDATE } from "./GUILD_UPDATE";
import { INTERACTION_CREATE } from "./INTERACTION_CREATE";
import { MESSAGE_CREATE } from "./MESSAGE_CREATE";
import { THREAD_DELETE } from "./THREAD_DELETE";

export const Actions = {
  CHANNEL_DELETE, 
  CHANNEL_UPDATE, 
  GUILD_CREATE, 
  GUILD_DELETE, 
  GUILD_UPDATE, 
  INTERACTION_CREATE, 
  MESSAGE_CREATE, 
  THREAD_DELETE
};